networks:
  moodle-network:

volumes:
  moodle_db:
  moodle_data:
  moodledata_data:

services:
  mariadb:
    image: bitnami/mariadb:${MARIADB_VERSION}
    container_name: moodle-db
    restart: always
    networks:
      - moodle-network
    environment:
      ALLOW_EMPTY_PASSWORD: yes
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_CHARACTER_SET: utf8mb4
      MARIADB_COLLATION: utf8mb4_unicode_ci
    volumes:
      - moodle_db:/var/lib/mysql

  moodle:
    image: bitnami/moodle:${MOODLE_VERSION}
    container_name: moodle
    networks:
      - moodle-network
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      BITNAMI_DEBUG: true
      ALLOW_EMPTY_PASSWORD: yes
      MOODLE_DATABASE_USER: ${DB_USER}
      MOODLE_DATABASE_PASSWORD: ${DB_PASS}
      MOODLE_DATABASE_NAME: ${DB_NAME}
      MOODLE_USERNAME: ${MOODLE_USER}
      MOODLE_PASSWORD: ${MOODLE_PASS}
    volumes:
      - moodle_data:/bitnami/moodle
      - moodledata_data:/bitnami/moodledata
    depends_on:
      - mariadb
