networks:
  moodle-network:

services:

  mariadb:
    image: bitnami/mariadb:latest
    container_name: moodle-db
    restart: always
    networks:
      - moodle-network
    environment:
      ALLOW_EMPTY_PASSWORD: yes
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}
      MARIADB_DATABASE: ${DB_NAME}
    volumes:
      - ./moodle_db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 45s

  moodle:
    image: bitnami/moodle:latest
    container_name: moodle
    networks:
      - moodle-network
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      ALLOW_EMPTY_PASSWORD: yes
      MOODLE_DATABASE_USER: ${DB_USER}
      MOODLE_DATABASE_PASSWORD: ${DB_PASS}
      MOODLE_DATABASE_NAME: ${DB_NAME}
      MOODLE_USERNAME: ${MOODLE_USER}
      MOODLE_PASSWORD: ${MOODLE_PASS}
    volumes:
      - ./moodle_data:/bitnami/moodle
      - ./moodledata_data:/bitnami/moodledata
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mariadb"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 45s
