networks:
  moodle-net:
    driver: bridge

services:

  mariadb:
    image: mariadb:11.6.2
    container_name: moodle-db
    networks:
      - moodle-net
    environment:
      - ALLOW_EMPTY_PASSWORD
      - MARIADB_USER
      - MARIADB_PASSWORD
      - MARIADB_DATABASE
    volumes:
      - ./moodle_db:/var/lib/mysql

  moodle:
    image: bitnami/moodle:4.4.4
    container_name: moodle
    ports:
      - "8080:8080"
      - "8443:8443"
    networks:
      - moodle-net
    environment:
      - ALLOW_EMPTY_PASSWORD
      - MOODLE_DATABASE_USER
      - MOODLE_DATABASE_PASSWORD
      - MOODLE_DATABASE_NAME
      - MOODLE_USERNAME
      - MOODLE_PASSWORD
    volumes:
      - ./moodle_data:/bitnami/moodle
      - ./moodledata_data:/bitnami/moodledata
    depends_on:
      - mariadb
